DEVICE_PATH := device/Oppo/A38

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a75

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := k69v1_64_k419
TARGET_NO_BOOTLOADER := true

# Platform
PRODUCT_PLATFORM := mt6768
TARGET_BOARD_PLATFORM := $(PRODUCT_PLATFORM)

BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 buildvariant=user
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 4096
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x04000000 --tags_offset 0x0E000000 --dtb $(TARGET_PREBUILT_DTB) --header_version $(BOARD_BOOT_HEADER_VERSION) --pagesize $(BOARD_KERNEL_PAGESIZE)

BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864

BOARD_USES_VENDOR_BOOTIMAGE := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true

BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_SIZE := 0
BOARD_HAS_LARGE_FILESYSTEM := true

TARGET_COPY_OUT_VENDOR := vendor
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

# TWRP Configuration
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_INCLUDE_REPACKTOOLS := true

# Storage System Operations and File Systems Compatibility
RECOVERY_SDCARD_ON_DATA := true
TARGET_USES_MKE2FS := true
TW_INCLUDE_FUSE_EXFAT := true
TW_INCLUDE_FUSE_NTFS := true
TW_INCLUDE_NTFS_3G := true
TW_NO_FASTBOOT_BOOT := true
TW_EXCLUDE_TWRP_APP := true

# Debug and Logging Modules
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true

# Graphics and Display Configuration
TW_FRAMERATE := 90

# Display Backlight Controls (Corrected for MediaTek mt6769 Kernel Layout)
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1024
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"

# Binary Executables Inclusion Configurations
TW_INCLUDE_BASH := true

# Peripheral Control Overrides
TW_EXCLUDE_DEFAULT_USB_INIT := true

#OF_STATUS_H := 100
#OF_STATUS_INDENT_LEFT := 48
#OF_STATUS_INDENT_RIGHT := 48
#OF_HIDE_NOTCH := 1
#OF_USE_GREEN_LED := 0
#F_FL_PATH1 := /sys/class/flashlight_core/flashlight/flashlight_torch
#TW_BATTERY_SYSFS_PATH := /sys/class/power_supply/battery

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := BGRA_8888